M48
; DRILL file {KiCad 9.0.7} date 2026-02-11T10:04:32-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-11T10:04:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.600
%
G90
G05
T1
X70.175Y-76.95
X70.175Y-87.05
T2
X66.5Y-60.5
X154.0Y-135.0
X229.5Y-60.5
X229.5Y-116.5
T3
X213.0Y-65.0
M30
